INSERT INTO CODE ( ORIGIN , DESTINY , TAX_PER_MINUTE ) VALUES ('011', '016', '1.90');
INSERT INTO CODE ( ORIGIN , DESTINY , TAX_PER_MINUTE ) VALUES ('016', '011', '2.90');
INSERT INTO CODE ( ORIGIN , DESTINY , TAX_PER_MINUTE ) VALUES ('011', '017', '1.70');
INSERT INTO CODE ( ORIGIN , DESTINY , TAX_PER_MINUTE ) VALUES ('017', '011', '2.70');
INSERT INTO CODE ( ORIGIN , DESTINY , TAX_PER_MINUTE ) VALUES ('011', '018', '0.90');
INSERT INTO CODE ( ORIGIN , DESTINY , TAX_PER_MINUTE ) VALUES ('018', '011', '1.90');
INSERT INTO PLAN ( TALK_MORE_PLAN ) VALUES (30);
INSERT INTO PLAN ( TALK_MORE_PLAN ) VALUES (60);
INSERT INTO PLAN ( TALK_MORE_PLAN ) VALUES (120);
